/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import javax.swing.JOptionPane;

/**
 *
 * @author Akses
 */
public class quarantinemobil extends javax.swing.JFrame {
    Boolean adatiket=null;
    Boolean adastnk=null;

    /**
     * Creates new form quarantine
     */
    public quarantinemobil() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        tiket.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bill = new javax.swing.JTextPane();
        tiketada = new javax.swing.JButton();
        tiketitdak = new javax.swing.JButton();
        stnkada = new javax.swing.JButton();
        stnktidak = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        tiket = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Karantina");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(bill);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 250, 110));

        tiketada.setText("Ada");
        tiketada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiketadaActionPerformed(evt);
            }
        });
        getContentPane().add(tiketada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        tiketitdak.setText("Tidak");
        tiketitdak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiketitdakActionPerformed(evt);
            }
        });
        getContentPane().add(tiketitdak, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        stnkada.setText("Ya");
        stnkada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stnkadaActionPerformed(evt);
            }
        });
        getContentPane().add(stnkada, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        stnktidak.setText("Tidak");
        stnktidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stnktidakActionPerformed(evt);
            }
        });
        getContentPane().add(stnktidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s/Mobil.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 150, 100));

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 340, 50));

        tiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiketActionPerformed(evt);
            }
        });
        getContentPane().add(tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 250, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s/check.jpg"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 150, 60));

        jScrollPane2.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 500, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s/quarantine.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "Telah Berhasil Checkout!", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
        new checkmobil().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiketActionPerformed

    private void tiketadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiketadaActionPerformed
tiket.setVisible(true);
tiketada.setVisible(false);
tiketitdak.setVisible(false);
adatiket=true;// TODO add your handling code here:
    }//GEN-LAST:event_tiketadaActionPerformed

    private void tiketitdakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiketitdakActionPerformed
tiketada.setVisible(false);
        adatiket=false;
// TODO add your handling code here:
    }//GEN-LAST:event_tiketitdakActionPerformed

    private void stnkadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stnkadaActionPerformed
        if (adatiket==null) {
            JOptionPane.showMessageDialog(null, "Cek ada tiket atau tidak terlebih dahulu!", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(adatiket==false){
            bill.setText("Denda karena tidak ada tiket dan membawa stnk: 5000 rupiah");
        }
        else if(adatiket=true){
            JOptionPane.showMessageDialog(null, "Tidak ada denda, problem terselesaikan", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
            new menupilih().setVisible(true);
            this.dispose();
        }
              // TODO add your handling code here:
    }//GEN-LAST:event_stnkadaActionPerformed

    private void stnktidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stnktidakActionPerformed
        if (adatiket==null) {
            JOptionPane.showMessageDialog(null, "Cek ada tiket atau tidak terlebih dahulu!", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(adatiket==false){
            bill.setText("Denda karena tidak ada tiket dan tidak membawa stnk: 10000 rupiah");
        }
        else if(adatiket=true){
            bill.setText("Denda karena tidak membawa stnk: 5000 rupiah");
        }// TODO add your handling code here:
    }//GEN-LAST:event_stnktidakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quarantinemobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quarantinemobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quarantinemobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quarantinemobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quarantinemobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane bill;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JButton stnkada;
    private javax.swing.JButton stnktidak;
    private javax.swing.JTextField tiket;
    private javax.swing.JButton tiketada;
    private javax.swing.JButton tiketitdak;
    // End of variables declaration//GEN-END:variables
}
